[package]
name = "bootloader"
version = "0.6.4"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
license = "MIT/Apache-2.0"
description = "An experimental pure-Rust x86 bootloader."
repository = "https://github.com/rust-osdev/bootloader"
edition = "2018"
build = "build.rs"

[[bin]]
name = "bootloader"
required-features = ["binary"]

[dependencies]
xmas-elf = { version = "0.6.2", optional = true }
x86_64 = { version = "0.7.2", optional = true }
usize_conversions = { version = "0.2.0", optional = true }
fixedvec = { version = "0.2.3", optional = true }

[dependencies.font8x8]
version = "0.2.4"
default-features = false
features = ["unicode"]
optional = true

[build-dependencies]
llvm-tools = "0.1"

[features]
default = []
binary = ["xmas-elf", "x86_64", "usize_conversions", "fixedvec"]
vga_320x200 = ["font8x8"]
recursive_page_table = []
map_physical_memory = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = false
debug = true

[package.metadata.bootloader]
target = "x86_64-bootloader.json"

[package.metadata.docs.rs]
features = [ "recursive_page_table", "map_physical_memory" ]
